### ISSUE TITLE
Error output when running truffle test.

### ISSUE THREAD

**Issue by HackFisher** [evolutionlandorg/market-contracts#37]
```
    1) "before all" hook: deploy and configure


  0 passing (2s)
  1 failing

  1) Contract: bancor deployment
       "before all" hook: deploy and configure:
     Error: VM Exception while processing transaction: out of gas
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by G-TipSolutions** [comment]
same here...ive tried everything...

  Contract: DecentralBank
    1) "before all" hook in "Contract: DecentralBank"


  0 passing (3s)
  1 failing

  1) Contract: DecentralBank
       "before all" hook in "Contract: DecentralBank":
     Error: Returned error: VM Exception while processing transaction: revert
      at Context.<anonymous> (C:/Users/bgsho/Solidity/defi-staking-app/test/decentralBank.tests.js:25:20)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)


    before(async () => {
        // Load Contracts
        // this.enableTimeouts(false)   <===I saw somewhere that this might work but not sure how to setup
        tether = await Tether.new()
        rwd = await RWD.new()
        decentralBank = await DecentralBank.new(rwd.address, tether.address)
        // Transfer all tokens to DecentralBank (1 million)
         await rwd.transfer(decentralBank.address, tokens('1000000'))
        
        // Transfer 100 mock Tethers to Customer
        await tether.transfer(customer, tokens('100'), {from: owner})
    })

**Comment by hujw77** [comment]
Please check out to dev branch， and use https://github.com/dapphub/dapptools
